### ISSUE TITLE
Mainrunner should run public static voidmain methods of main folder too not just the test sources

### ISSUE THREAD

**Issue by nagkumar** [sormuras/mainrunner#10]
I am seeing this runner does not pickup all the main methods of main source code..

this engine does not run NewCodeInMain main method

![image](https://user-images.githubusercontent.com/332234/232409145-c601ea0d-9cca-407a-bc3c-36b90c5b3a6a.png)

![image](https://user-images.githubusercontent.com/332234/232409252-9937f1ee-1997-4346-88d3-38741d846cdc.png)

but only running the NewCodeInTest in test folder

if any thing can get into test folder, people would use junit 5 normal test framework why would they use main method in test folder classes.

The only reason main(string[] ags) exists is to test classes as part of the main class.. hence support for running all the main folder sources  that have main method should be run.

**Comment by sormuras** [comment]
> I am seeing this runner does not pickup all the main methods of main source code.
> ...
> but only running the NewCodeInTest in test folder

That is on purpose. 

> The only reason main(string[] ags) exists is to test classes as part of the main class.

No. In my book they exist to start main programs, possibly with an UI or other long-running (server) processes.

This engine will focus on test sources - as it is a test engine (implementation).
